# Generated by Django 2.0.4 on 2018-10-22 20:46

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('distric', models.CharField(max_length=256)),
                ('street1', models.CharField(max_length=256)),
                ('street2', models.CharField(max_length=256)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tooltip', models.CharField(max_length=256)),
                ('src', models.ImageField(blank=True, null=True, upload_to=api.models.img_path)),
            ],
        ),
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('price_negotiatian', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('currency', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('floor_number', models.SmallIntegerField()),
                ('number_of_bathrooms', models.SmallIntegerField()),
                ('number_of_bedrooms', models.SmallIntegerField()),
                ('number_of_livingrooms', models.SmallIntegerField()),
                ('number_of_kitchens', models.SmallIntegerField()),
                ('number_of_store', models.SmallIntegerField()),
                ('tiles', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('gypsum', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('payment_terms', models.SmallIntegerField()),
                ('unit_of_payment_terms', models.CharField(max_length=100)),
                ('electricity', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('water', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('parking_space', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('length_unit', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('payment_terms', models.SmallIntegerField()),
                ('unit_of_payment_terms', models.CharField(max_length=100)),
            ],
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('area', models.FloatField()),
                ('area_unit', models.CharField(max_length=10)),
                ('carrying_capacity', models.IntegerField()),
                ('electricity', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('water', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('generator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('parking_space', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('carrying_capacity', models.IntegerField()),
                ('bed_type', models.CharField(max_length=100)),
                ('electricity', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('allow_cooking', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('tables', models.SmallIntegerField()),
                ('chairs', models.SmallIntegerField()),
                ('water', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('water_tanks', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('transport', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('generator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('sucurity', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('payment_terms', models.SmallIntegerField()),
                ('unit_of_payment_terms', models.CharField(max_length=100)),
                ('parking_space', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('number_of_bathrooms', models.SmallIntegerField()),
                ('number_of_bedrooms', models.SmallIntegerField()),
                ('number_of_livingrooms', models.SmallIntegerField()),
                ('number_of_kitchens', models.SmallIntegerField()),
                ('number_of_store', models.SmallIntegerField()),
                ('tiles', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('gypsum', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('type_of_windows', models.CharField(max_length=100)),
                ('payment_terms', models.SmallIntegerField()),
                ('unit_of_payment_terms', models.CharField(max_length=100)),
                ('electricity', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('water', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('fance', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('parking_space', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('length_unit', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('is_registered', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('length_unit', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('floor_number', models.SmallIntegerField()),
                ('number_of_rooms', models.SmallIntegerField()),
                ('airconditioning', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('generator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('sucurity', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('payment_terms', models.SmallIntegerField()),
                ('unit_of_payment_terms', models.CharField(max_length=100)),
                ('parking_space', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('elevator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('water', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
            bases=('api.property',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Property')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('length_unit', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('bathroom', models.CharField(choices=[('Self Contained', 'Self Contained'), ('Public', 'Public')], max_length=100)),
                ('tiles', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('gypsum', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
                ('type_of_windows', models.CharField(max_length=100)),
                ('number_of_windows', models.SmallIntegerField()),
                ('payment_terms', models.SmallIntegerField()),
                ('unit_of_payment_terms', models.CharField(max_length=100)),
                ('electricity', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('water', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('fance', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('parking_space', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
            bases=('api.property',),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyOwner'),
        ),
        migrations.AddField(
            model_name='property',
            name='potentials',
            field=models.ManyToManyField(to='api.Potential'),
        ),
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(to='api.Service'),
        ),
        migrations.AddField(
            model_name='picture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        ),
        migrations.AddField(
            model_name='phone',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyOwner'),
        ),
    ]
