# Generated by Django 2.0.4 on 2018-10-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_negotiatian',
            new_name='price_negotiationn',
        ),
    ]
