# Generated by Django 3.0.2 on 2020-01-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200128_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='user',
            new_name='owner',
        ),
    ]
