# Generated by Django 2.1.2 on 2019-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181120_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='rent', max_length=5),
            preserve_default=False,
        ),
    ]
