# Generated by Django 2.1.2 on 2018-10-28 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181024_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.PropertyOwner'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.Property'),
        ),
    ]
