# Generated by Django 2.1.2 on 2018-10-29 20:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181028_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='electricity',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor_number',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='gypsum',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bathrooms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bedrooms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_kitchens',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_livingrooms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_store',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking_space',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='payment_terms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tiles',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_of_payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='water',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='frame',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='length_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='frame',
            name='payment_terms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='unit_of_payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='frame',
            name='width',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='area_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='hall',
            name='carrying_capacity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='electricity',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hall',
            name='generator',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hall',
            name='parking_space',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hall',
            name='water',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='allow_cooking',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='carrying_capacity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='chairs',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='electricity',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='generator',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='parking_space',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='payment_terms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='sucurity',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='tables',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='transport',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='unit_of_payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='water',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='water_tanks',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='electricity',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='fance',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='gypsum',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_bathrooms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_bedrooms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_kitchens',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_livingrooms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_store',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking_space',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='payment_terms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='tiles',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='type_of_windows',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='unit_of_payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='water',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='is_registered',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='land',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='length_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='land',
            name='width',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='distric',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='street1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='street2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='office',
            name='airconditioning',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='office',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='elevator',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='office',
            name='floor_number',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='generator',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='office',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='length_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='office',
            name='number_of_rooms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='parking_space',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='office',
            name='payment_terms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='sucurity',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='office',
            name='unit_of_payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='office',
            name='water',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='office',
            name='width',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='src',
            field=models.ImageField(default=False, upload_to=api.models.img_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='tooltip',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='property',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='potentials',
            field=models.ManyToManyField(blank=True, to='api.Potential'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_negotiation',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.Service'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('Self Contained', 'Self Contained'), ('Public', 'Public')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='electricity',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='fance',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='gypsum',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='length_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_windows',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='parking_space',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='payment_terms',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tiles',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_of_windows',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='unit_of_payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='water',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='width',
            field=models.FloatField(blank=True),
        ),
    ]
