# Generated by Django 3.0.7 on 2020-06-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200630_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='unit_of_payment_terms',
            new_name='payment_terms_unit',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='unit_of_payment_terms',
            new_name='payment_terms_unit',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='unit_of_payment_terms',
            new_name='payment_terms_unit',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='unit_of_payment_terms',
            new_name='payment_terms_unit',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='unit_of_payment_terms',
            new_name='payment_terms_unit',
        ),
    ]
