# Generated by Django 3.0.7 on 2020-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200703_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_rate_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
