# Generated by Django 3.0.7 on 2020-07-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_property_price_rate_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_negotiation',
            new_name='is_price_negotiable',
        ),
    ]
