# Generated by Django 3.0.7 on 2020-07-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200703_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_properties',
            field=models.ManyToManyField(to='api.Property'),
        ),
    ]
