# Generated by Django 3.0.7 on 2020-08-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200802_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='distric',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street2',
        ),
    ]
