# Generated by Django 3.0.7 on 2020-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_room_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='area',
        ),
        migrations.RemoveField(
            model_name='land',
            name='length',
        ),
        migrations.RemoveField(
            model_name='land',
            name='width',
        ),
        migrations.AddField(
            model_name='land',
            name='square_meters',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
